apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      containers:
      - name: debug-container
        image: curlimages/curl:7.87.0
        command: ['/bin/sh', '-c', '--']
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        args: ['while true; do sleep 30; done;']